CHANGELOG.md, spnego/_version.py, spnego/sspi.py
WSMV when using SSPI does not actually provide a padding buffer to the SSPI call so we should not do so ourselves. There has been a long internal conversation with the protocol team for WSMV and they have confirmed that when it calls SSPI it does it with the headers
1. `SECBUFFER_TOKEN`
2. `SECBUFFER_DATA`
This is cause of the weird hacks in [gssapi](https://github.com/jborean93/pyspnego/blob/04c9d183778e0b8d7fa7bfe170d7b405d5e496ae/spnego/gss.py#L493-L515) to deal with RC4 when the padding is expected by GSSAPI but SSPI does not provide it in this protocol. So while we must still supply the padding buffer for GSSAPI we can replicate the exact behaviour when running on Windows. I'm not sure how I tested this before but I can confirm that this works with both AES and RC4 on Windows.
Fixes …
=> Fix up WinRM wrapping on SSPI

CHANGELOG.md, azure-pipelines.yml, spnego/_version.py, spnego/negotiate.py
The [RFC for SPNEGO](https://www.rfc-editor.org/rfc/rfc4178.html#section-4.2.1) states that `negState: request-mic` should only be sent in the first reply from the acceptor
> The sender indicates that the exchange of MIC tokens, as described in Section 5, will be REQUIRED if per-message integrity services are available on the mechanism context to be established.  This value SHALL only be present in the first reply from the target.
It seems like GSSAPI and SSPI are lenient in that it doesn't validate this requirement so it was never an issue for those implementations but others may not be the same. This fixes the logic to conform to the RFC and work with implementations that enforce this.
This issue was found in https://github.com/jborean93/smbprotocol/issues/61 where the NetApp GSSAPI …
=> Fix up request-mic for Negotiate auth

CHANGELOG.md, spnego/_version.py, spnego/ntlm.py, tests/test_ntlm.py
There may be some edge cases where a user wants to blank out the workstation field in an NTLM exchange. The `gss-ntlmssp` library uses the env var `NETBIOS_COMPUTER_NAME` as a way to override the value and to ensure consistency between that library and the Python one here we will also use that env var.
=> Add workstation override to match gss-ntlmssp

CHANGELOG.md, azure-pipelines.yml, spnego/iov.py
This type class should really be an `IntEnum` as it's meant to represent a single value.
Fixes https://github.com/jborean93/pyspnego/issues/10
=> Fix enum usage for Python 3.10

CHANGELOG.md, spnego/gss.py, tests/test_auth.py
By passing in `None` to `gssapi.SecurityContext` the target SPN is used to select the default credential in a collection ccache.
Fixes https://github.com/jborean93/pyspnego/issues/15
=> Use None for GSSAPI credential with no username set

CHANGELOG.md, spnego/negotiate.py, tests/test_auth.py
Older SPNEGO logic with NTLM (and possibly others) had the `mechListMIC` in the `NegTokenResp` set to the same value as the `responseToken`. While most modern servers no longer do this it's still possible to encounter something out there that still follows this behaviour causing the client to fail to the authentication because the `mechListMIC` was invalid
> SpnegoError (6): A token had an invalid Message Integrity Check (MIC), Context: Invalid Message integrity Check (MIC) detected
When checking MIT krb5 we can see that they ignore the duplicate value when it matches what is set for `responseToken` so this behaviour is just replicated here https://github.com/krb5/krb5/blob/3f5a348287646d65700854650fe668b9c4249013/src/lib/gssapi/spnego/spnego_mech.c#L3734-L3744.
Fixes …
=> Fix SPNEGO mechListMIC logic

spnego/_ntlm_raw/crypto.py, spnego/auth.py, tests/test_auth.py
Use NTLMProxy if explicitly specified and password is NTLM hash
pyspnego prefers the platform implementations (e.g. SSPI) over the python implementations (e.g. NTLM). The SSPI implementation does not allow the user to specify a NT or LM hash for use with NTLM authentication, whereas the NTLMProxy does. In this specific case, we don't want pyspnego to prefer SSPIProxy, but instead use NTLMProxy.
=> Ntlm hash on windows

CHANGELOG.md, spnego/_negotiate.py, tests/test_negotiate.py
Ensures any invalid inputs sent into the NegotiateProxy are raises as an
InvalidTokenError rather than the generic struct.error. This aligns the
behaviour of the pyspnego Negotiate provider with the platform specific
providers when attempting to parse an invalid input token..
Fixes https://github.com/jborean93/pyspnego/issues/24
=> Treat invalid token inputs as InvalidTokenError

CHANGELOG.md, src/spnego/_credssp.py, src/spnego/_version.py, src/spnego/tls.py, tests/test_auth.py, tests/test_credssp.py
The use of `ssl.PROTOCOL_TLS` is deprecated in favour of `ssl.PROTOCOL_TLS_CLIENT` and `ssl.PROTOCOL_TLS_SERVER`. While this is a slight breaking change as the client needs to pass in the usage the default is `initiate` which should cover the main scenarios when using this.
=> Stop using deprecated TLS context

CHANGELOG.md, pyproject.toml, src/spnego/__init__.py, src/spnego/_context.py, src/spnego/_credential.py, src/spnego/_credssp.py, src/spnego/_gss.py, src/spnego/_negotiate.py, src/spnego/_ntlm.py, src/spnego/_sspi.py, src/spnego/auth.py, tests/_ntlm_raw/test_messages.py, tests/integration/main.yml, tests/integration/templates/test_integration.py.tmpl, tests/test_auth.py, tests/test_gss.py, tests/test_negotiate.py, tests/test_ntlm.py, tests/test_sspi.py
This PR adds support for supplying different credential types for authentication. This allows for some more advanced scenarios like using Kerberos from a keytab/ccache, NTLM with the explicit NT/LM hash. It also exposes an interface for anonymous credentials or the extra CredSSP delegation credentials for future work when needed.
Unfortunately the current UI is hardwired to username/password as 2 arguments so this will continue going forward with an ultimate goal to deprecate this at some point in the future (way in the future).
=> Support for different credential types

CHANGELOG.md, src/spnego/_context.py, src/spnego/_credssp.py, src/spnego/_version.py, tests/test_auth.py
Added the ability to specify the minimum CredSSP protocol version that
the caller allows. Talking to a peer that does not meet this minimum
requirement will result in an InvalidTokenError. This allows the caller
to only allow peers that have mitigated CVE-2018-0886 or any future CVEs
that result in a new protocol version.
Also adds the auth_stage and protocol_version extra info for a CredSSP
context proxy allowing the caller to inspect the protocol version that
was ultimately negotiated between the initiator and acceptor as well as
provide more details on the authentication process in CredSSP for more
context around error messages.
=> CredSSP min protocol and stage information

CHANGELOG.md, src/spnego/_negotiate.py
Ensure an empty context list will not cause an exception when attempting
to retrieve attributes like client_principal, negotiate_protocol and so
on. This can occur when the client proxy has been created but before any
stepping has been done.
Fixes https://github.com/jborean93/pyspnego/issues/33
=> Fix retrieving negotiate attributes at the start

CHANGELOG.md, src/spnego/_gss.py, src/spnego/_version.py
Makes sure that when calling gss-ntlmssp over GSSAPI that it will add
the MIC to the last authentication message even when not being wrapped
through SPNEGO. This is done by query a specific context attribute of
the NTLM security context that notifies gss-ntlmssp that a MIC can be
added.
=> Ensure gss-ntlmssp adds NTLM MIC

CHANGELOG.md, src/spnego/_sspi.py, src/spnego/_sspi_raw/sspi.pxd, src/spnego/_sspi_raw/sspi.pyi, src/spnego/_sspi_raw/sspi.pyx, src/spnego/_version.py, tests/_sspi_raw/test_sspi.py, tests/test_sspi.py
Fix errors when running with heap allocation checks on Windows. This
moves all the management of the SecBuffer objects to the Python code to
keep the Cython management simple. It also exposed some of the
inefficiencies that are in place where memory was copied to avoid it
mutating which can be addressed in a separate PR.
Fixes: https://github.com/jborean93/pyspnego/issues/40
=> Fix Heap Allocation Errors on Windows

.github/workflows/ci.yml
macOS-10.15 is deprecated and going through some brownouts and needs to be updated to the latest.
=> Test against latest macOS CI version

.github/workflows/ci.yml, src/spnego/_asn1.py, src/spnego/_sspi.py, src/spnego/channel_bindings.py, tests/test_channel_bindings.py
Python 3.11 changed the way enums are represented with `str()`. This makes sure our use of this stays the same across versions by manually using the original form for things that are publicly exposed.
Fixes https://github.com/jborean93/pyspnego/issues/42
=> Fix enum str representation for python 3.11 changes

CHANGELOG.md, src/spnego/_gss.py
The `gssapi` extra requirement is set to `>= 1.5.0` for compatibility with what RHEL 8 ships with. This should be bumped when RHEL 8 compat is no longer desired.
Fixes: https://github.com/jborean93/pyspnego/issues/43
=> Fix old gssapi version incompatibilities

.github/workflows/ci.yml, CHANGELOG.md, MANIFEST.in, README.md, build_helpers/lib.sh, build_helpers/run-container.sh, pyproject.toml, setup.py, src/spnego/_gss.py, src/spnego/_version.py, src/spnego/tls.py, tests/integration/inventory.yml, tests/integration/main.yml
This takes full advantage of PEP 517 with build time dependencies for the Cython code and mostly read only metadata for the project itself.
Part of this change means the sdist no longer contains the cythonised files and will be automatically cythonised at install time if the wheel is not being used.
=> Migrate setup.py config to pyproject.toml

tests/conftest.py
Call `locale.setlocale()` only if the current locale is not UTF-8
already, in order to resolve errors when the system used to run tests
is using a UTF-8 locale but does not have the en_US.UTF-8 locale
installed as reported in https://bugs.gentoo.org/865205.
While at it, fix the logic to ensure that:
locale.setlocale(locale.LC_ALL, "")
is called prior to the locale manipulation, in order to actually respect
the system locale.  See https://docs.python.org/3/library/locale.html
=> Call locale.setlocale() only if the current locale is not UTF-8

CHANGELOG.md, src/spnego/_gss.py, src/spnego/_version.py
Ignores the error GSS_S_NO_CONTEXT when stepping through tokens on GSSAPI. MIT krb5 before 1.14.x raised this error on a context that is incomplete causing an error that can safely be ignored.
Fixes: https://github.com/jborean93/pyspnego/issues/55
=> Ignore GSS_S_NO_CONTEXT on GSSAPI stepping

CHANGELOG.md, build_helpers/run-container.sh, src/spnego/_context.py, src/spnego/_credssp.py, src/spnego/_gss.py, src/spnego/_negotiate.py, src/spnego/_ntlm.py, src/spnego/_sspi.py, tests/test_auth.py
Adds the new_context() function that will create a new context based on the existing contexts credentials and options. This is designed to be a more efficient way to recreate a brand new security context. For example it can recreate the context with a cached provider specific credential rather than retrieving a new one for each context. This is important when using Kerberos authentication as the retrieved TGT can be cached and reused across multiple contexts.
=> Add new_context() option to copy a context

.github/workflows/ci.yml, CHANGELOG.md, README.md, src/spnego/_context.py, src/spnego/_gss.py, src/spnego/auth.py, tests/integration/Vagrantfile, tests/integration/inventory.yml, tests/integration/main.yml, tests/test_auth.py, tests/test_exceptions.py, tests/test_gss.py
Removes the use of gssntlmssp through the GSSAPIProxy provider. This simplifies the codebase as now it just needs to deal with Kerberos and different gssntlmssp versions that might be installed.
=> Remove use of gssntlmssp

.gitignore, CHANGELOG.md, src/spnego/_context.py, src/spnego/_credssp.py, src/spnego/_gss.py, src/spnego/_negotiate.py, src/spnego/_ntlm.py, src/spnego/_ntlm_raw/crypto.py, src/spnego/_sspi.py, src/spnego/_version.py, tests/integration/main.yml, tests/integration/templates/generate_cert.sh.tmpl, tests/integration/templates/test_integration.py.tmpl, tests/integration/tests.yml, tests/test_auth.py, tests/test_gss.py, tests/test_ntlm.py
Adds the no_integrity flag which can be used to explicitly tell the underlying provider that integrity and confidentiality is not to be used. This is used for Kerberos authentication on both SSPI and GSSAPI as by default it will always negotiate both integrity and confidentiality even if not explicitly requested.
This commit also adds support for specifying the channel binding token during the step calls. This makes it easier to create a security context and only provide connection level details when the first step is required.
=> Add no_integrity support and bindings in step

CHANGELOG.md, src/spnego/_ntlm.py, src/spnego/_version.py
Always set the NTLM Negotiate version flag and field when generating the message. This aligns the client behaviour to match with SSPI which also sets this value. It should improve compatibility with some NTLM servers which expect the version flag to be set in subsequent token exchanges.
Fixes: https://github.com/jborean93/smbprotocol/issues/216
=> Set NTLM Negotiate Version field

CHANGELOG.md, pyproject.toml, src/spnego/_sspi.py, tests/test_sspi.py
Renames the sspi dependency to sspic to reflect the name change. This was done to avoid a conflict with pywin32's sspi package that it exports.
=> Rename sspi dep to sspic

CHANGELOG.md, src/spnego/_gss.py, src/spnego/_ntlm_raw/crypto.py, src/spnego/_version.py, tests/test_gss.py, tests/test_ntlm.py
Added support for using gMSA/machine account passwords with the provided string. The string must have been decoded from the raw UTF-16-LE bytes using the surrogatepass handler for this to work.
=> Add support for gMSA/machine passwords

.vscode/settings.json, CHANGELOG.md, src/spnego/tls.py
Python 3.12 deprecated datetime.datetime.utcnow() in favour of datetime.datetime.now(datetime.timezone.utc) to ensure that a non naive dt object was created. This PR moved to the newer syntax where the older one was used.
Fixes: https://github.com/jborean93/pyspnego/issues/78
=> Move away from dep datetime call

src/spnego/_credential.py
This is a fix for NTLM authentication for user account with no password. We encountered this regression in pywinrm after requests-ntlm was updated to 1.2.0.
=> Fix handling of empty passwords

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml, requirements-test.txt, src/spnego/_ntlm_raw/crypto.py, src/spnego/_version.py
Starting with cryptography-44.0.0 the ARC4 cipher was relocated to a module for deprecated ciphers. It needs to be imported from there now.
=> Fix deprecation warning for Cryptography 44.0.0 or newer

CHANGELOG.md, src/spnego/_credssp.py, src/spnego/_version.py
Fix up the TLS handshake code when on a LibreSSL based CPython install. While most installs will use OpenSSL it seems like some BSD based ports still patch in LibreSSL which changes some of the TLS packets emitted in a handshake.
Fixes: https://github.com/jborean93/pyspnego/issues/90
=> Fix CredSSP acceptor with LibreSSL

CHANGELOG.md, pyproject.toml, src/spnego/_credential.py, src/spnego/_sspi.py, src/spnego/auth.py, tests/integration/main.yml, tests/integration/templates/test_integration.py.tmpl, tests/test_sspi.py
Adds support for using a keytab on Windows with SSPI. This will only work with Kerberos authentication but it unifies the credential behaviour across the two platforms.
Fixes: https://github.com/jborean93/pyspnego/issues/95
=> Add support for Keytabs on Windows
